<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>navbar_login</name>
   <tag></tag>
   <elementGuidId>68bb9082-c4c2-40a4-bcfe-fd24c601adc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer_menu_top</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
