<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_loginPassword</name>
   <tag></tag>
   <elementGuidId>11b338b9-8bcb-4306-b910-258075a545a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginFrm_password</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
