<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_loginName</name>
   <tag></tag>
   <elementGuidId>fa1eb0a2-50f2-4d0d-b056-0985a87431fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginFrm_loginname</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
